version: '3.1' # specify docker-compose version

volumes:
  # Set up with `docker volume create ...`. See docker/README.md for more info.
  amicus_data_volume:
    external: true
  amicus_data_tests_volume:
    external: true
  
services:
  # Runs from the latest release
  amicus_bot:
    image: mauceric/amicus_bot
#    restart: always
#    environment:
#     - PYTHONPATH="${PYTHONPATH}:/Users/mauceric/PRG/amicus_bot"
    volumes:
      - amicus_data_volume:/data
    # Used for allowing connections to homeservers hosted on the host machine
    # (while docker host mode is still broken on Linux).
    #
    # Defaults to 127.0.0.1 and is set in docker/.env
    extra_hosts:
      - localhost:192.168.1.100


  # Builds and runs a development container from local code
  test:
#    environment:
#      - PYTHONPATH="${PYTHONPATH}:/home/mauceric/amicus_bot/tests"
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
      # Build arguments may be specified here
      # args:
      #  PYTHON_VERSION: 3.8
    volumes:
      - /Users/mauceric/PRG/amicus_bot/tests:/data
    # Used for allowing connections to homeservers hosted on the host machine
    # (while docker host networking mode is still broken on Linux).
    #
    # Defaults to 127.0.0.1 and is set in docker/.env
    extra_hosts:
      - "localhost:${HOST_IP_ADDRESS}"

  